fond_user_formulaire:
    resource: "@FONDUserBundle/Controller/FormulaireController.php"
    type:     annotation

fond_user:
    resource: "@FONDUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
